services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
        POSTGRES_DB: ${POSTGRES_DB:-currency_converter}

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
